rstudio support
Support RStudio based workloads in kubernetes_driver. Add sidecar proxy
container to instance deployments. Change templating to Jinja2 from
python string format() to support curly braces in templates.

Changes
- add nginx proxy container to deployment
  - reverse proxy traffic to the instance container
  - optionally rewrite path and redirect urls for RStudio
  - can also be used for authentication in the future
- create ConfigMap per instance
  - generate nginx config based on proxy_rewrite parameter
  - store generated proxy configuration in a configmap
  - can be used to store for example startup scripts in the future
- change the service to always target nginx port 8080
- add resource limits to deployment as openshift requires these for
  multi-container pods
- use Jinja2 for formatting templates
- add Jinja2 as an explicit dependency
- fix failure condition where a delayed pod creation would be treated as
  a direct failure
- add RStudio template and environment to devel dataset

diff --git a/pebbles/drivers/provisioning/templates/deployment.yaml b/pebbles/drivers/provisioning/templates/deployment.yaml
--- a/pebbles/drivers/provisioning/templates/deployment.yaml
+++ b/pebbles/drivers/provisioning/templates/deployment.yaml
@@ -1,60 +1,87 @@
 apiVersion: apps/v1
 kind: Deployment
 metadata:
-  name: "{name}"
+  name: "{{name}}"
 spec:
   selector:
     matchLabels:
-      name: "{name}"
+      name: "{{name}}"
   template:
     metadata:
       labels:
-        name: "{name}"
+        name: "{{name}}"
     spec:
+      # no default service account token for the pod
       automountServiceAccountToken: false
       # tolerate user role node taint
       tolerations:
-      - key: "role"
-        value: "user"
-        effect: "NoSchedule"
+        - key: "role"
+          value: "user"
+          effect: "NoSchedule"
       initContainers:
-      - name: autodownload
-        image: "{image}"
-        imagePullPolicy: IfNotPresent
-        env: []
-        command:
-          - sh
-          - -c
-          - |
-            if [ -z $AUTODOWNLOAD_URL ]; then exit 0; fi;
-            cd /data;
-            if [ $AUTODOWNLOAD_METHOD = "http-get" ]; then wget $AUTODOWNLOAD_URL || echo "download failed"; fi;
-            if [ $AUTODOWNLOAD_METHOD = "git-clone" ]; then git clone $AUTODOWNLOAD_URL || echo "cloning failed"; fi;
-        volumeMounts:
-          - mountPath: "/data"
-            name: data
+        - name: autodownload
+          image: "{{image}}"
+          imagePullPolicy: IfNotPresent
+          env: [ ]
+          command:
+            - sh
+            - -c
+            - |
+              if [ -z $AUTODOWNLOAD_URL ]; then exit 0; fi;
+              cd /data;
+              if [ $AUTODOWNLOAD_METHOD = "http-get" ]; then wget $AUTODOWNLOAD_URL || echo "download failed"; fi;
+              if [ $AUTODOWNLOAD_METHOD = "git-clone" ]; then git clone $AUTODOWNLOAD_URL || echo "cloning failed"; fi;
+          volumeMounts:
+            - mountPath: "/data"
+              name: data
       containers:
-      - name: pebbles-instance
-        image: "{image}"
-        imagePullPolicy: IfNotPresent
-        args: []
-        env: []
-        volumeMounts:
-          - mountPath: "{volume_mount_path}"
-            name: data
-          - mountPath: "{volume_mount_path}/shared-data"
-            name: shared-data
-        # generic check if the pod is accepting connections, poll every 1 second
-        readinessProbe:
-          tcpSocket:
-            port: {port}
-            periodSeconds: 1
+        - name: proxy
+          image: docker.io/bitnami/nginx:1.19.8
+          imagePullPolicy: IfNotPresent
+          volumeMounts:
+            - name: nginx-config
+              mountPath: /opt/bitnami/nginx/conf/server_blocks
+          resources:
+            requests:
+              cpu: "200m"
+              memory: "64Mi"
+            limits:
+              cpu: "200m"
+              memory: "64Mi"
+
+        - name: pebbles-instance
+          image: "{{image}}"
+          imagePullPolicy: IfNotPresent
+          args: [ ]
+          env: [ ]
+          volumeMounts:
+            - mountPath: "{{volume_mount_path}}"
+              name: data
+          # generic check if the pod is accepting connections, poll every 1 second
+          readinessProbe:
+            tcpSocket:
+              port: {{port}}
+              periodSeconds: 1
+          resources:
+            requests:
+              cpu: "100m"
+              memory: "{{memory_limit}}"
+            limits:
+              cpu: "1800m"
+              memory: "{{memory_limit}}"
+
       volumes:
         - name: data
           persistentVolumeClaim:
-            claimName: "{pvc_name_user}"
+            claimName: "{{pvc_name_user}}"
             readOnly: false
+        - name: nginx-config
+          configMap:
+            name: "{{name}}"
+            items:
+              - key: "proxy.conf"
+                path: "proxy.conf"
         - name: shared-data
           persistentVolumeClaim:
-            claimName: "{pvc_name_shared}"
-            readOnly: {shared_data_read_only_mode}
+            claimName: "{{pvc_name_shared}}"
+            readOnly: {{shared_data_read_only_mode}}
